#!/bin/sh -e

# build
#	Simple wiringPi build and install script
#
#	Copyright (c) 2012-2015 Gordon Henderson
#################################################################################
# This file is part of wiringPi:
#	A "wiring" library for the Raspberry Pi
#
#    wiringPi is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Lesser General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    wiringPi is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with wiringPi.  If not, see <http://www.gnu.org/licenses/>.
#################################################################################
#
# wiringPi is designed to run on a Raspberry Pi only.
#	However if you're clever enough to actually look at this script to
#	see why it's not building for you, then good luck.
#
#	To everyone else: Stop using cheap alternatives. Support the
#	Raspberry Pi Foundation	as they're the only ones putting money
#	back into education!
#################################################################################

check_make_ok() {
  if [ $? != 0 ]; then
    echo ""
    echo "Make Failed..."
    echo "Please check the messages and fix any problems. If you're still stuck,"
    echo "then raise a GitHub issue with the output and as many details as you can"
    echo "  https://github.com/WiringPi/WiringPi/issues"
    echo ""
    exit 1
  fi
}

sudo=${WIRINGPI_SUDO-sudo}

config=$2

# Allow: no config (default rpi build), or specific configuration
if [ $# -gt 2 ]; then
  echo "Usage: $0 [clean | uninstall] [config]"
  echo "Supported configurations: 'rpios' | 'generic'"
  exit 1
fi

if [ x$1 = "xhelp" ] || [ x$1 = "x--help" ]; then
  echo "Usage: $0 [clean | uninstall] [config]"
  echo "Supported configurations: 'rpios' | 'generic'"
  exit 0
fi

action="$1"
config=""
if [ x$2 = "xgeneric" ]; then
  config="generic"
elif [ x$2 = "xrpios" ]; then
  config="rpios"
fi

if [ x$action = "xclean" ]; then
  cd wiringPi
  echo -n "wiringPi:   " ; make clean $config
  cd ../devLib
  echo -n "DevLib:     " ; make clean $config
  cd ../gpio
  echo -n "gpio:       " ; make clean $config
  cd ../examples
  echo -n "Examples:   " ; make clean $config
  cd Gertboard
  echo -n "Gertboard:  " ; make clean $config
  cd ../PiFace
  echo -n "PiFace:     " ; make clean $config
  cd ../q2w
  echo -n "Quick2Wire: " ; make clean $config
  cd ../PiGlow
  echo -n "PiGlow:     " ; make clean $config
  cd ../scrollPhat
  echo -n "scrollPhat: " ; make clean $config
  cd ../..
  echo -n "Deb: " ; rm  -f debian-template/wiringpi*.deb
  echo
  exit
fi

if [ x$action = "xuninstall" ]; then
  cd wiringPi
  echo -n "wiringPi: " ; $sudo make uninstall $config
  cd ../devLib
  echo -n "DevLib:   " ; $sudo make uninstall $config
  cd ../gpio
  echo -n "gpio:     " ; $sudo make uninstall $config
  exit
fi

# Main build logic

echo "wiringPi Build script"
echo "====================="
echo

hardware=`fgrep Hardware /proc/cpuinfo | head -1 | awk '{ print $3 }'`

echo
echo "WiringPi Library"
cd wiringPi
make -j5 $config
check_make_ok
$sudo make install $config
check_make_ok

echo
echo "WiringPi Devices Library"
cd ../devLib
make -j5 $config
check_make_ok
$sudo make install $config
check_make_ok

echo
echo "GPIO Utility"
cd ../gpio
make -j5 $config
check_make_ok
$sudo make install $config
check_make_ok

# echo
# echo "wiringPi Daemon"
# cd ../wiringPiD
# make -j5
# check_make_ok
# $sudo make install
# check_make_ok

# echo
# echo "Examples"
# cd ../examples
# make
# cd ..

echo
echo All Done.
echo ""
echo "NOTE: To compile programs with wiringPi, you need to add:"
echo "    -lwiringPi"
echo "  to your compile line(s) To use the Gertboard, MaxDetect, etc."
echo "  code (the devLib), you need to also add:"
echo "    -lwiringPiDev"
echo "  to your compile line(s)."
echo ""
